/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 computer.gltf --transform
Author: EdwinRC (https://sketchfab.com/Edwin3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-gaming-setup-69145aa6647a42849487b6c3404f5075
Title: Low Poly Gaming Setup
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/computer-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-0.11, -4.32, 2.6]} rotation={[0, 0, -3.14]} scale={0.25}>
          <lineSegments geometry={nodes.Object_5.geometry} material={materials.material_0} />
          <mesh geometry={nodes['Green-material'].geometry} material={materials.Green} />
          <mesh geometry={nodes['Black-material'].geometry} material={materials.Black} />
        </group>
        <group position={[-12.11, 3.49, 5.31]} rotation={[0, 0, 0.55]} scale={0.14}>
          <mesh geometry={nodes['Gray-material'].geometry} material={materials.Gray} />
          <mesh geometry={nodes['Mouse1-material'].geometry} material={materials.Mouse1} />
        </group>
        <group position={[-0.16, 5.6, 5.26]} scale={0.12}>
          <mesh geometry={nodes['Gray-material_1'].geometry} material={materials.Gray} />
          <mesh geometry={nodes['Red-material'].geometry} material={materials.material} />
          <mesh geometry={nodes['Mouse1-material_1'].geometry} material={materials.Mouse1} />
          <mesh geometry={nodes['Blue-material'].geometry} material={materials.Lamp} />
          <mesh geometry={nodes['Yellow-material'].geometry} material={materials.Yellow} />
        </group>
        <group position={[7.85, 4.6, 8.46]} rotation={[0, 0, 2.46]} scale={2.75}>
          <mesh geometry={nodes['Mouse1-material_3'].geometry} material={materials.Mouse1} />
          <mesh geometry={nodes['Gray-material_2'].geometry} material={materials.Gray} />
        </group>
        <group position={[2.82, 5.09, 8.66]} rotation={[1.99, 0.04, -1.59]} scale={0.21}>
          <mesh geometry={nodes['Mouse1-material_4'].geometry} material={materials.Mouse1} />
          <mesh geometry={nodes['Green-material_1'].geometry} material={materials.Green} />
        </group>
        <group position={[3.95, 1.46, 4.93]} rotation={[0, 0, -1.24]} scale={0.18}>
          <mesh geometry={nodes['Mouse1-material_5'].geometry} material={materials.Mouse1} />
          <mesh geometry={nodes['Mouse2-material'].geometry} material={materials.Mouse2} />
        </group>
        <group position={[-10.19, 11.27, -0.19]} scale={2.08}>
          <mesh geometry={nodes['Mouse1-material_6'].geometry} material={materials.Mouse1} />
          <mesh geometry={nodes['Red-material_1'].geometry} material={materials.material} />
          <mesh geometry={nodes['Green-material_2'].geometry} material={materials.Green} />
          <mesh geometry={nodes['L_Blue-material_1'].geometry} material={materials.L_Blue} />
        </group>
        <mesh geometry={nodes['Floor-material'].geometry} material={materials.Floor} position={[-0.19, 0, 1.5]} />
        <mesh geometry={nodes['Mat007-material'].geometry} material={materials.Mat007} position={[-0.19, 0, 1.5]} />
        <mesh geometry={nodes['Desk_Wood1-material'].geometry} material={materials.Desk_Wood1} position={[-0.22, -0.5, -0.51]} />
        <mesh geometry={nodes['Right_Scn-material'].geometry} material={materials.Right_Scn} position={[-12.11, 3.49, 5.31]} rotation={[0, 0, 0.55]} scale={0.14} />
        <mesh geometry={nodes['Left_Scn-material'].geometry} material={materials.Left_Scn} position={[7.85, 4.6, 8.46]} rotation={[0, 0, 2.46]} scale={2.75} />
        <mesh geometry={nodes['Middle_Scn-material'].geometry} material={materials.Middle_Scn} position={[-0.16, 5.6, 5.26]} scale={0.12}  />
        <mesh geometry={nodes['L_Blue-material'].geometry} material={materials.L_Blue} position={[-0.13, 2.44, 4.95]} rotation={[0, 0, -3.14]} scale={0.72} />
        <mesh geometry={nodes['Mouse1-material_2'].geometry} material={materials.Mouse1} position={[-0.72, 2.06, 5.64]} scale={0.19} />
        <mesh geometry={nodes['Gray-material_3'].geometry} material={materials.Gray} position={[-0.13, 2.44, 4.95]} rotation={[0, 0, -3.14]} scale={0.72} />
      </group>
    </group>
  )
}

useGLTF.preload('/computer-transformed.glb')
