/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 robot.gltf --transform
Author: gbaldsing (https://sketchfab.com/GBaldsing)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/junk-yard-robot-boy-1fac6302809c4f039b4e34c0cd1146b7
Title: Junk Yard Robot Boy
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export  default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/robot-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" position={[-9.13, -10.33, -0.54]} rotation={[-Math.PI / 2, 0, 0]} scale={0.02}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="GLTF_created_3">
                <group name="RAMP1_96" position={[0, 0, 1.67]} scale={0}>
                  <group name="RAMP1PIV_97" position={[0, 0, -1.67]}>
                    <group name="RAMPShape1_98">
                      <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.GLSLShader8} />
                    </group>
                  </group>
                </group>
                <primitive object={nodes.GLTF_created_3_rootJoint} />
                <skinnedMesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.ArmsShader} skeleton={nodes.Object_6.skeleton} />
                <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.ArmsShader} skeleton={nodes.Object_12.skeleton} />
                <skinnedMesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.ArmsShader} skeleton={nodes.Object_14.skeleton} />
                <skinnedMesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.ArmsShader} skeleton={nodes.Object_16.skeleton} />
                <skinnedMesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.ArmsShader} skeleton={nodes.Object_18.skeleton} />
                <skinnedMesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.ArmsShader} skeleton={nodes.Object_20.skeleton} />
                <skinnedMesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.ArmsShader} skeleton={nodes.Object_23.skeleton} />
                <skinnedMesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.ArmsShader} skeleton={nodes.Object_26.skeleton} />
                <skinnedMesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.ArmsShader} skeleton={nodes.Object_27.skeleton} />
                <skinnedMesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.ArmsShader} skeleton={nodes.Object_30.skeleton} />
                <skinnedMesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.ArmsShader} skeleton={nodes.Object_31.skeleton} />
                <skinnedMesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.ArmsShader} skeleton={nodes.Object_34.skeleton} />
                <skinnedMesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.ArmsShader} skeleton={nodes.Object_37.skeleton} />
                <skinnedMesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.ArmsShader} skeleton={nodes.Object_40.skeleton} />
                <skinnedMesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials.ArmsShader} skeleton={nodes.Object_43.skeleton} />
                <skinnedMesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.ArmsShader} skeleton={nodes.Object_46.skeleton} />
                <skinnedMesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.ArmsShader} skeleton={nodes.Object_49.skeleton} />
                <skinnedMesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.ArmsShader} skeleton={nodes.Object_52.skeleton} />
                <skinnedMesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.ArmsShader} skeleton={nodes.Object_53.skeleton} />
                <skinnedMesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.ArmsShader} skeleton={nodes.Object_56.skeleton} />
                <skinnedMesh name="Object_59" geometry={nodes.Object_59.geometry} material={materials.ArmsShader} skeleton={nodes.Object_59.skeleton} />
                <skinnedMesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.ArmsShader} skeleton={nodes.Object_62.skeleton} />
                <skinnedMesh name="Object_65" geometry={nodes.Object_65.geometry} material={materials.ArmsShader} skeleton={nodes.Object_65.skeleton} />
                <skinnedMesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.ArmsShader} skeleton={nodes.Object_68.skeleton} />
                <skinnedMesh name="Object_71" geometry={nodes.Object_71.geometry} material={materials.ArmsShader} skeleton={nodes.Object_71.skeleton} />
                <skinnedMesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.ArmsShader} skeleton={nodes.Object_74.skeleton} />
                <skinnedMesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials.ArmsShader} skeleton={nodes.Object_77.skeleton} />
                <skinnedMesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.ArmsShader} skeleton={nodes.Object_80.skeleton} />
                <skinnedMesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials.ArmsShader} skeleton={nodes.Object_83.skeleton} />
                <skinnedMesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.ArmsShader} skeleton={nodes.Object_86.skeleton} />
                <skinnedMesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.lowerShader} skeleton={nodes.Object_88.skeleton} />
                <skinnedMesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.lowerShader} skeleton={nodes.Object_90.skeleton} />
                <skinnedMesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.lowerShader} skeleton={nodes.Object_92.skeleton} />
                <skinnedMesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.lowerShader} skeleton={nodes.Object_94.skeleton} />
                <skinnedMesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.lowerShader} skeleton={nodes.Object_96.skeleton} />
                <skinnedMesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.lowerShader} skeleton={nodes.Object_98.skeleton} />
                <skinnedMesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.lowerShader} skeleton={nodes.Object_100.skeleton} />
                <skinnedMesh name="Object_103" geometry={nodes.Object_103.geometry} material={materials.lowerShader} skeleton={nodes.Object_103.skeleton} />
                <skinnedMesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.lowerShader} skeleton={nodes.Object_106.skeleton} />
                <skinnedMesh name="Object_109" geometry={nodes.Object_109.geometry} material={materials.lowerShader} skeleton={nodes.Object_109.skeleton} />
                <skinnedMesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.lowerShader} skeleton={nodes.Object_112.skeleton} />
                <skinnedMesh name="Object_115" geometry={nodes.Object_115.geometry} material={materials.lowerShader} skeleton={nodes.Object_115.skeleton} />
                <skinnedMesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.lowerShader} skeleton={nodes.Object_118.skeleton} />
                <skinnedMesh name="Object_121" geometry={nodes.Object_121.geometry} material={materials.lowerShader} skeleton={nodes.Object_121.skeleton} />
                <skinnedMesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials.lowerShader} skeleton={nodes.Object_124.skeleton} />
                <skinnedMesh name="Object_127" geometry={nodes.Object_127.geometry} material={materials.lowerShader} skeleton={nodes.Object_127.skeleton} />
                <skinnedMesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials.lowerShader} skeleton={nodes.Object_130.skeleton} />
                <skinnedMesh name="Object_133" geometry={nodes.Object_133.geometry} material={materials.ArmsShader} skeleton={nodes.Object_133.skeleton} />
                <skinnedMesh name="Object_136" geometry={nodes.Object_136.geometry} material={materials.ArmsShader} skeleton={nodes.Object_136.skeleton} />
                <skinnedMesh name="Object_139" geometry={nodes.Object_139.geometry} material={materials.TapeCTRLS} skeleton={nodes.Object_139.skeleton} />
                <skinnedMesh name="Object_141" geometry={nodes.Object_141.geometry} material={materials.UpperBody} skeleton={nodes.Object_141.skeleton} />
                <skinnedMesh name="Object_144" geometry={nodes.Object_144.geometry} material={materials.UpperBody} skeleton={nodes.Object_144.skeleton} />
                <skinnedMesh name="Object_145" geometry={nodes.Object_145.geometry} material={materials.UpperBody} skeleton={nodes.Object_145.skeleton} />
                <skinnedMesh name="Object_146" geometry={nodes.Object_146.geometry} material={materials.UpperBody} skeleton={nodes.Object_146.skeleton} />
                <skinnedMesh name="Object_149" geometry={nodes.Object_149.geometry} material={materials.UpperBody} skeleton={nodes.Object_149.skeleton} />
                <skinnedMesh name="Object_152" geometry={nodes.Object_152.geometry} material={materials.UpperBody} skeleton={nodes.Object_152.skeleton} />
                <skinnedMesh name="Object_155" geometry={nodes.Object_155.geometry} material={materials.UpperBody} skeleton={nodes.Object_155.skeleton} />
                <skinnedMesh name="Object_158" geometry={nodes.Object_158.geometry} material={materials.UpperBody} skeleton={nodes.Object_158.skeleton} />
                <skinnedMesh name="Object_161" geometry={nodes.Object_161.geometry} material={materials.UpperBody} skeleton={nodes.Object_161.skeleton} />
                <skinnedMesh name="Object_162" geometry={nodes.Object_162.geometry} material={materials.UpperBody} skeleton={nodes.Object_162.skeleton} />
                <skinnedMesh name="Object_164" geometry={nodes.Object_164.geometry} material={materials.ArmsShader} skeleton={nodes.Object_164.skeleton} />
                <skinnedMesh name="Object_166" geometry={nodes.Object_166.geometry} material={materials.ArmsShader} skeleton={nodes.Object_166.skeleton} />
                <skinnedMesh name="Object_168" geometry={nodes.Object_168.geometry} material={materials.ArmsShader} skeleton={nodes.Object_168.skeleton} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/robot-transformed.glb')
