/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Room.gltf --transform
Author: letsmakecoolart (https://sketchfab.com/seriouscat)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/room-42a3d38aaa5c47f1ab039b27df1278c7
Title: Room
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Room-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.47, 0.9, -1.74]} scale={0.08}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Pen_Blue_Blue} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Pen_Blue} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Pen_Greens} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Pen_Pink.002']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Pen_Pink} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Pen_Pink.001']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Pen_Pink.007']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['Pen_Pink.006']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Pen_Purple} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Pen_Red} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['Pen_Green.002']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['Pen_Pink.008']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['Pen_Pink.004']} />
        <mesh geometry={nodes.Object_19.geometry} material={materials['Pen_Pink.005']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Pen_Gree} />
        <mesh geometry={nodes.Object_21.geometry} material={materials['Pen_Pink.003']} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.Pen_Vyan} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Pen_Wood} />
      </group>
      <group position={[0.74, 0.99, -0.83]} rotation={[-Math.PI, -0.68, -Math.PI]} scale={[0.12, 0.1, 0.12]}>
        <mesh geometry={nodes.Object_25.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Object_26.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.Coffee} />
        <mesh geometry={nodes.Object_28.geometry} material={materials['Glass.001']} />
        <mesh geometry={nodes.Object_29.geometry} material={materials['Board.001']} />
        <mesh geometry={nodes.Object_30.geometry} material={materials['Material.019']} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.Paper_White} />
        <mesh geometry={nodes.Object_32.geometry} material={materials['Material.020']} />
      </group>
      <group position={[0.38, 0.9, -0.81]} rotation={[0, -0.19, 0]}>
        <mesh geometry={nodes.Object_34.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.Cubik_white} />
        <mesh geometry={nodes.Object_36.geometry} material={materials['Material.018']} />
      </group>
      <group position={[-1.54, 0.95, -1.5]} rotation={[-0.13, 0.01, 0]}>
        <mesh geometry={nodes.Object_41.geometry} material={materials.Cubik_white} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.Keyboard_glossGLOSS} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.Cat_grey} />
        <mesh geometry={nodes.Object_44.geometry} material={materials['Keyboard_glossGLOSS.002']} />
        <mesh geometry={nodes.Object_45.geometry} material={materials['Keyboard_glossGLOSS.001']} />
        <mesh geometry={nodes.Object_46.geometry} material={materials['Keyboard_glossGLOSS.003']} />
        <mesh geometry={nodes.Object_47.geometry} material={materials['Keyboard_glossGLOSS.004']} />
      </group>
      <group position={[0.29, 1.14, -1.71]} rotation={[0.01, 0.02, 0.09]}>
        <mesh geometry={nodes.Object_49.geometry} material={materials.Paper_White} />
        <mesh geometry={nodes.Object_50.geometry} material={materials['Material.019']} />
      </group>
      <group position={[-0.55, 0.97, -1.74]} rotation={[0.73, 0.03, -0.44]} scale={[0.01, 0, 0.01]}>
        <mesh geometry={nodes.Object_56.geometry} material={materials['Material.022']} />
        <mesh geometry={nodes.Object_57.geometry} material={materials['Material.013']} />
      </group>
      <group position={[-1.13, 0.07, 0.06]} rotation={[0, 1.16, 0]} scale={[1.07, 1.07, 1.59]}>
        <mesh geometry={nodes.Object_59.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.Keyboard_rough} />
        <mesh geometry={nodes.Object_61.geometry} material={materials['Material.025']} />
      </group>
      <group rotation={[Math.PI / 2, 0, 1.55]} scale={0.19}>
        <mesh geometry={nodes.Object_80.geometry} material={materials.Plant_01} position={[-6.15, 10.46, -13.93]} rotation={[-2.59, 0.24, -0.25]} scale={0.38} />
        <mesh geometry={nodes.Object_82.geometry} material={materials.Plant_01} position={[-5.99, 10.58, -13.93]} rotation={[-2.81, -0.43, -0.28]} scale={[0.17, 0.43, 0.43]} />
      </group>
      <group position={[0.69, 0.9, -1.74]} rotation={[-Math.PI, -0.73, -Math.PI]} scale={0.08}>
        <mesh geometry={nodes.Object_86.geometry} material={materials.Pen_Blue_Blue} />
        <mesh geometry={nodes.Object_87.geometry} material={materials.Pen_Blue} />
        <mesh geometry={nodes.Object_88.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Object_89.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Object_91.geometry} material={materials.Pen_Greens} />
        <mesh geometry={nodes.Object_92.geometry} material={materials['Pen_Pink.002']} />
        <mesh geometry={nodes.Object_93.geometry} material={materials.Pen_Pink} />
        <mesh geometry={nodes.Object_94.geometry} material={materials['Pen_Pink.001']} />
        <mesh geometry={nodes.Object_96.geometry} material={materials['Pen_Pink.006']} />
        <mesh geometry={nodes.Object_97.geometry} material={materials.Pen_Purple} />
        <mesh geometry={nodes.Object_99.geometry} material={materials['Pen_Green.002']} />
        <mesh geometry={nodes.Object_100.geometry} material={materials['Pen_Pink.008']} />
        <mesh geometry={nodes.Object_101.geometry} material={materials['Pen_Pink.004']} />
        <mesh geometry={nodes.Object_102.geometry} material={materials['Pen_Pink.005']} />
        <mesh geometry={nodes.Object_109.geometry} material={materials.Pen_Wood} />
        <mesh geometry={nodes.Object_90.geometry} material={materials['Pen_Pink.009']} />
        <mesh geometry={nodes.Object_95.geometry} material={materials['Pen_Pink.007']} />
        <mesh geometry={nodes.Object_98.geometry} material={materials.Pen_Red} />
        <mesh geometry={nodes.Object_103.geometry} material={materials.Pen_Gree} />
        <mesh geometry={nodes.Object_104.geometry} material={materials['Pen_Pink.003']} />
        <mesh geometry={nodes.Object_105.geometry} material={materials.Pen_White} />
        <mesh geometry={nodes.Object_106.geometry} material={materials.Pen_Black} />
        <mesh geometry={nodes.Object_107.geometry} material={materials.Pen_Yellow} />
        <mesh geometry={nodes.Object_108.geometry} material={materials.Pen_Vyan} />
      </group>
      <group position={[-0.46, 0.91, -1.06]} rotation={[0, 0.27, -0.01]} scale={[1.62, 1.62, 1.91]}>
        <mesh geometry={nodes.Object_111.geometry} material={materials.Keyboard_rough} />
        <mesh geometry={nodes.Object_112.geometry} material={materials.Keyboard_glossGLOSS} />
        <mesh geometry={nodes.Object_113.geometry} material={materials['Material.004']} />
      </group>
      <group position={[0.26, 0.87, -1.31]} rotation={[0, 1.55, 0]} scale={1.27}>
        <mesh geometry={nodes.Object_115.geometry} material={materials.Pen_Wood} />
        <mesh geometry={nodes.Object_116.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_117.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Object_118.geometry} material={materials['Pen_Green.001']} />
        <mesh geometry={nodes.Object_119.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Object_120.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Object_121.geometry} material={materials.Cubik_white} />
        <mesh geometry={nodes.Object_122.geometry} material={materials.Keyboard_gloss} />
        <mesh geometry={nodes.Object_123.geometry} material={materials.Paper_White} />
        <mesh geometry={nodes.Object_124.geometry} material={materials['Material.008']} />
      </group>
      <group position={[-0.51, 0.91, -1.73]} rotation={[-0.01, 0, 0]} scale={[0.47, 0.3, 0.03]}>
        <mesh geometry={nodes.Object_128.geometry} material={materials.Keyboard_rough} />
        <mesh geometry={nodes.Object_129.geometry} material={materials.Silver_plastic} />
      </group>
      <group position={[0.28, 0.9, -1.7]} rotation={[0, 0.03, 0]} scale={0.07}>
        <mesh geometry={nodes.Object_131.geometry} material={materials.Board_green} />
        <mesh geometry={nodes.Object_132.geometry} material={materials['Material.032']} />
        <mesh geometry={nodes.Object_133.geometry} material={materials['Material.033']} />
      </group>
      <group position={[-0.05, 0, 0]}>
        <mesh geometry={nodes.Object_139.geometry} material={materials.Keyboard_rough} />
        <mesh geometry={nodes.Object_140.geometry} material={materials['Screen.002']} />
        <mesh geometry={nodes.Object_141.geometry} material={materials['Screen.001']} />
        <mesh geometry={nodes.Object_142.geometry} material={materials['Screen.003']} />
        <mesh geometry={nodes.Object_143.geometry} material={materials['Screen.007']} />
      </group>
      <group position={[-0.92, 0.9, -1.63]} rotation={[-0.03, 0.4, -0.01]} scale={0.05}>
        <mesh geometry={nodes.Object_147.geometry} material={materials.Cubik_blue} />
        <mesh geometry={nodes.Object_148.geometry} material={materials.Cubik_yellow} />
        <mesh geometry={nodes.Object_149.geometry} material={materials.Cubik_rose} />
        <mesh geometry={nodes.Object_150.geometry} material={materials.Cubik_orange} />
        <mesh geometry={nodes.Object_151.geometry} material={materials.Cubik_green} />
        <mesh geometry={nodes.Object_152.geometry} material={materials.Cubik_white} />
      </group>
      <group position={[-0.61, 0.9, -1.35]} rotation={[0, 0.09, -0.02]} scale={1.33}>
        <mesh geometry={nodes.Object_154.geometry} material={materials.Keyboard_glossGLOSS} />
        <mesh geometry={nodes.Object_155.geometry} material={materials.Keyboard_gloss} />
        <mesh geometry={nodes.Object_156.geometry} material={materials.Keyboard_rough} />
      </group>
      <group position={[-0.85, 0.92, -0.72]} rotation={[-Math.PI, -0.05, -Math.PI]} scale={1.24}>
        <mesh geometry={nodes.Object_160.geometry} material={materials.Keyboard_rough} />
        <mesh geometry={nodes.Object_161.geometry} material={materials.Keyboard_gloss} />
      </group>
      <group position={[-2.09, 0.78, -0.39]} scale={1.23}>
        <mesh geometry={nodes.Object_163.geometry} material={materials.Keyboard_gloss} />
        <mesh geometry={nodes.Object_164.geometry} material={materials.Keyboard_glossGLOSS} />
      </group>
      <group position={[-0.51, 1.27, -1.71]} rotation={[-0.01, 0, 0]} scale={[0.47, 0.3, 0.03]}>
        <mesh geometry={nodes.Object_168.geometry} material={materials.Screen} />
        <mesh geometry={nodes.Object_169.geometry} material={materials['Screen.005']} />
        <mesh geometry={nodes.Object_170.geometry} material={materials['Screen.001']} />
        <mesh geometry={nodes.Object_171.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_172.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Object_173.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Object_174.geometry} material={materials['Material.024']} />
      </group>
      <group position={[0.6, 1.21, -1.36]} rotation={[0.03, -0.03, 1.15]} scale={2.13}>
        <mesh geometry={nodes.Object_176.geometry} material={materials.Plant_02} />
        <mesh geometry={nodes.Object_177.geometry} material={materials.lambert37} />
        <mesh geometry={nodes.Object_178.geometry} material={materials['Material.017']} />
      </group>
      <group position={[-1.22, 1.51, -1.66]} rotation={[-Math.PI, 1.04, -Math.PI]} scale={0.23}>
        <mesh geometry={nodes.Object_182.geometry} material={materials['Screen.004']} />
        <mesh geometry={nodes.Object_183.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_184.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_185.geometry} material={materials['Screen.002']} />
      </group>
      <group position={[-0.76, 1.02, -1.73]} rotation={[-0.01, 0, 0]} scale={[0.6, 0.09, 0.03]}>
        <mesh geometry={nodes.Object_193.geometry} material={materials.Paper_Yellow} />
        <mesh geometry={nodes.Object_194.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-0.79, 1.87, -1.88]} scale={[1.34, 1.18, 1.18]}>
        <mesh geometry={nodes.Object_218.geometry} material={materials.Paper_White} />
        <mesh geometry={nodes.Object_219.geometry} material={materials['Screen.006']} />
        <mesh geometry={nodes.Object_220.geometry} material={materials['Material.027']} />
        <mesh geometry={nodes.Object_221.geometry} material={materials['Material.028']} />
      </group>
      <group position={[0.47, 1.87, -1.86]} rotation={[0, 0, -Math.PI]} scale={[-2.54, 2.34, 1.83]}>
        <mesh geometry={nodes.Object_223.geometry} material={materials.Paper_White} />
        <mesh geometry={nodes.Object_224.geometry} material={materials.Board_green} />
        <mesh geometry={nodes.Object_225.geometry} material={materials['Screen.007']} />
      </group>
      <group position={[1.37, 1.87, -1.86]} rotation={[0, 0, -Math.PI]} scale={[-2.54, 2.34, 1.83]}>
        <mesh geometry={nodes.Object_227.geometry} material={materials.Paper_White} />
        <mesh geometry={nodes.Object_228.geometry} material={materials.Board_green} />
      </group>
      <group position={[0.23, 2.67, -1.85]} rotation={[0, 0, -Math.PI]} scale={[-3.09, 2.84, 2.22]}>
        <mesh geometry={nodes.Object_230.geometry} material={materials.Paper_White} />
        <mesh geometry={nodes.Object_231.geometry} material={materials.Board_green} />
      </group>
      <group position={[-0.73, 2.58, -1.86]} rotation={[0, 0, -Math.PI]} scale={[-2.08, 2.4, 1.88]}>
        <mesh geometry={nodes.Object_233.geometry} material={materials.Paper_White} />
        <mesh geometry={nodes.Object_234.geometry} material={materials.Board_green} />
      </group>
      <group position={[-1.28, 2.5, -1.87]} rotation={[0, 0, -Math.PI]} scale={[-0.72, 0.84, 0.66]}>
        <mesh geometry={nodes.Object_236.geometry} material={materials.Paper_White} />
        <mesh geometry={nodes.Object_237.geometry} material={materials.Board_green} />
      </group>
      <group position={[-1.61, 2.5, -1.87]} rotation={[0, 0, -Math.PI]} scale={[-0.64, 1.3, 0.66]}>
        <mesh geometry={nodes.Object_239.geometry} material={materials.Paper_White} />
        <mesh geometry={nodes.Object_240.geometry} material={materials.Board_green} />
      </group>
      <group position={[-1.86, 1.87, -1.57]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[1, 0.87, 0.87]}>
        <mesh geometry={nodes.Object_242.geometry} material={materials.Paper_White} />
        <mesh geometry={nodes.Object_243.geometry} material={materials.Board_green} />
      </group>
      <group position={[-1.86, 2.1, -1.57]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[1, 0.87, 0.87]}>
        <mesh geometry={nodes.Object_245.geometry} material={materials.Paper_White} />
        <mesh geometry={nodes.Object_246.geometry} material={materials.Board_green} />
      </group>
      <group position={[1.26, 2.56, -1.86]} rotation={[0, 0, -Math.PI]} scale={[-1.53, 2.34, 1.83]}>
        <mesh geometry={nodes.Object_248.geometry} material={materials.Paper_White} />
        <mesh geometry={nodes.Object_249.geometry} material={materials.Board_green} />
      </group>
      <group position={[1.82, 2.56, -1.86]} rotation={[0, 0, -Math.PI]} scale={[-1.25, 2.73, 1.83]}>
        <mesh geometry={nodes.Object_251.geometry} material={materials.Paper_White} />
        <mesh geometry={nodes.Object_252.geometry} material={materials.Board_green} />
      </group>
      <group position={[-0.22, 1.78, -1.89]} rotation={[-3.14, -0.04, 2.17]} scale={[-0.14, 0.08, 0.08]}>
        <mesh geometry={nodes.Object_262.geometry} material={materials.lENTA} />
        <mesh geometry={nodes.Object_263.geometry} material={materials.Paper_White} />
        <mesh geometry={nodes.Object_264.geometry} material={materials['Screen.002']} />
        <mesh geometry={nodes.Object_265.geometry} material={materials['Material.031']} />
      </group>
      <group position={[0.14, 1, -1.5]} scale={[0.79, 0.77, 0.77]}>
        <mesh geometry={nodes.Object_293.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Object_294.geometry} material={materials['Material.008']} />
      </group>
      <group position={[0.29, 0.97, -1.5]} rotation={[-0.01, 0.01, 0.13]} scale={[0.36, 0.77, 0.77]}>
        <mesh geometry={nodes.Object_296.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Object_297.geometry} material={materials.Silver_plastic} />
        <mesh geometry={nodes.Object_298.geometry} material={materials.Paper_White} />
      </group>
      <group position={[-0.34, 0.93, -1.7]} rotation={[0, 0.38, -0.04]} scale={0.43}>
        <mesh geometry={nodes.Object_302.geometry} material={materials.Keyboard_gloss} />
        <mesh geometry={nodes.Object_303.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Object_304.geometry} material={materials.Yellow} />
        <mesh geometry={nodes.Object_305.geometry} material={materials.material} />
      </group>
      <group position={[-0.39, 0.93, -1.68]} scale={0.43}>
        <mesh geometry={nodes.Object_307.geometry} material={materials.White} />
        <mesh geometry={nodes.Object_308.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Object_309.geometry} material={materials.Yellow} />
        <mesh geometry={nodes.Object_310.geometry} material={materials.material} />
      </group>
      <group position={[-1.08, 0.93, -0.99]} rotation={[-Math.PI, 1.15, Math.PI / 2]} scale={[0.63, 0.61, 0.61]}>
        <mesh geometry={nodes.Object_312.geometry} material={materials.Paper_White} />
        <mesh geometry={nodes.Object_313.geometry} material={materials.Metal} />
        <mesh geometry={nodes.Object_314.geometry} material={materials['Material.003']} />
      </group>
      <group position={[-0.05, 0.91, -1.32]} rotation={[2, 0.32, -0.97]} scale={[-0.01, 0.13, 0.01]}>
        <mesh geometry={nodes.Object_316.geometry} material={materials.Pen_Pink} />
        <mesh geometry={nodes.Object_317.geometry} material={materials.Pen_Wood} />
      </group>
      <group position={[-1.38, 1.98, -1.92]} rotation={[1.57, 0, 0]} scale={1.06}>
        <mesh geometry={nodes.Object_319.geometry} material={materials['Material.028']} />
        <mesh geometry={nodes.Object_320.geometry} material={materials.Paper_White} />
        <mesh geometry={nodes.Object_321.geometry} material={materials['Material.030']} />
      </group>
      <group position={[-1.56, 0.9, -0.71]} rotation={[0, 0.08, 0]} scale={[0.71, 0.71, 0.63]}>
        <mesh geometry={nodes.Object_323.geometry} material={materials.Board} />
        <mesh geometry={nodes.Object_324.geometry} material={materials.material_97} />
        <mesh geometry={nodes.Object_325.geometry} material={materials.Scotch} />
      </group>
      <group position={[0.49, 0.9, -1.22]} rotation={[-Math.PI, 0.47, -Math.PI]} scale={1.27}>
        <mesh geometry={nodes.Object_327.geometry} material={materials.Keyboard_gloss} />
        <mesh geometry={nodes.Object_328.geometry} material={materials.Keyboard_rough} />
        <mesh geometry={nodes.Object_329.geometry} material={materials.Metal} />
      </group>
      <group position={[0.24, 0.9, -1.03]}>
        <mesh geometry={nodes.Object_331.geometry} material={materials.Coffee} />
        <mesh geometry={nodes.Object_332.geometry} material={materials.material_99} />
        <mesh geometry={nodes.Object_333.geometry} material={materials.material_97} />
      </group>
      <group position={[1.13, 1.25, -1.34]} rotation={[-1.76, -0.84, -2.09]}>
        <mesh geometry={nodes.Object_339.geometry} material={materials.Cat_grey} />
        <mesh geometry={nodes.Object_340.geometry} material={materials.Keyboard_rough} />
        <mesh geometry={nodes.Object_341.geometry} material={materials.Keyboard_glossGLOSS} />
        <mesh geometry={nodes.Object_342.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Object_343.geometry} material={materials['Material.008']} />
      </group>
      <group position={[-1.22, 0.95, -1.12]} rotation={[1.76, 0.49, -0.38]} scale={[-0.01, 0.13, 0.01]}>
        <mesh geometry={nodes.Object_345.geometry} material={materials.Pen_Black} />
        <mesh geometry={nodes.Object_346.geometry} material={materials.Pen_Wood} />
      </group>
      <mesh geometry={nodes.Object_38.geometry} material={materials.Keyboard_rough} />
      <mesh geometry={nodes.Object_39.geometry} material={materials.Keyboard_gloss} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.material_0} position={[0.07, 1.18, -1.67]} scale={[0.03, 0.27, 0.17]} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.material_0} position={[0.33, 1.18, -1.67]} rotation={[0.05, 0, -0.04]} scale={[0.03, 0.27, 0.17]} />
      <mesh geometry={nodes.Object_63.geometry} material={materials.Keyboard_gloss} position={[-2.08, 1.15, -0.24]} />
      <mesh geometry={nodes.Object_65.geometry} material={materials.Keyboard_gloss} position={[-0.26, 0.95, -1.1]} rotation={[-2.46, -1.16, -2.47]} scale={0.46} />
      <mesh geometry={nodes.Object_67.geometry} material={materials.Keyboard_gloss} position={[-2.11, 1.16, -1.13]} rotation={[0, 0, -Math.PI / 2]} scale={0.35} />
      <mesh geometry={nodes.Object_69.geometry} material={materials.material_0} position={[-0.05, 0, 0]} />
      <mesh geometry={nodes.Object_71.geometry} material={materials.Keyboard_gloss} position={[-2.01, 1.09, -1.03]} rotation={[-0.11, -0.48, -1.54]} scale={0.35} />
      <mesh geometry={nodes.Object_73.geometry} material={materials.Keyboard_gloss} position={[-2.02, 1.16, -1.13]} rotation={[0, 0, -Math.PI / 2]} scale={0.35} />
      <mesh geometry={nodes.Object_75.geometry} material={materials.Keyboard_gloss} position={[-1.92, 1.09, -1.38]} rotation={[-1.67, 0.07, 1.1]} scale={0.35} />
      <mesh geometry={nodes.Object_77.geometry} material={materials.Keyboard_gloss} position={[-1.92, 1.06, -1.24]} rotation={[-1.67, 0.07, 1.1]} scale={0.35} />
      <mesh geometry={nodes.Object_84.geometry} material={materials.Paper_White} position={[1.21, 0.91, -0.92]} scale={[0.14, 0.19, 0.19]} />
      <mesh geometry={nodes.Object_126.geometry} material={materials['Glass.001']} position={[1.18, 0.9, -0.84]} scale={0.8} />
      <mesh geometry={nodes.Object_135.geometry} material={materials['Material.008']} position={[-1.08, 0.9, -1.46]} scale={0.08} />
      <mesh geometry={nodes.Object_137.geometry} material={materials.Keyboard_rough} position={[0.03, 0.9, -1.38]} scale={[0.6, 0.11, 0.6]} />
      <mesh geometry={nodes.Object_145.geometry} material={materials.Keyboard_rough} position={[-0.35, 0.9, -0.91]} rotation={[0, 0.06, 0]} scale={[0.46, 0.02, 0.28]} />
      <mesh geometry={nodes.Object_158.geometry} material={materials['Material.011']} position={[0.22, 0.35, -1.28]} />
      <mesh geometry={nodes.Object_166.geometry} material={materials.Plant_01} position={[-1.11, 1.11, -1.48]} rotation={[1.24, -0.56, 0.26]} />
      <mesh geometry={nodes.Object_180.geometry} material={materials['Screen.003']} position={[-1.77, 1.61, -1.35]} rotation={[-Math.PI, -0.4, -Math.PI]} scale={0.69} />
      <mesh geometry={nodes.Object_187.geometry} material={materials['Material.003']} position={[-1.63, 1.6, -1.39]} />
      <mesh geometry={nodes.Object_189.geometry} material={materials['Material.003']} position={[-1.67, 1.23, -1.38]} scale={[1, 0.41, 1]} />
      <mesh geometry={nodes.Object_191.geometry} material={materials.Keyboard_gloss} position={[-1.59, 0.51, -1.74]} />
      <mesh geometry={nodes.Object_196.geometry} material={materials.Skull} position={[-1.32, 0.89, -1.56]} rotation={[-0.4, 0.44, 0.22]} scale={2.38} />
      <mesh geometry={nodes.Object_198.geometry} material={materials['lambert37.001']} position={[-2.09, 0.78, -0.39]} scale={1.23} />
      <mesh geometry={nodes.Object_200.geometry} material={materials.Keyboard_gloss} position={[-2.09, 0.78, -0.39]} scale={1.23} />
      <mesh geometry={nodes.Object_202.geometry} material={materials.Keyboard_gloss} position={[-0.32, 0.92, -0.85]} />
      <mesh geometry={nodes.Object_204.geometry} material={materials.Wall_blue} scale={1.89} />
      <mesh geometry={nodes.Object_206.geometry} material={materials.material_0} scale={2.04} />
      <mesh geometry={nodes.Object_208.geometry} material={materials.material_0} scale={1.89} />
      <mesh geometry={nodes.Object_210.geometry} material={materials.material_0} position={[-2.3, 0.74, -0.39]} scale={[1.89, 1.89, 2.01]} />
      <mesh geometry={nodes.Object_212.geometry} material={materials.material_0} position={[-2, 1.53, -0.29]} scale={1.89} />
      <mesh geometry={nodes.Object_214.geometry} material={materials['Material.008']} position={[-2, 1.53, -0.29]} scale={1.89} />
      <mesh geometry={nodes.Object_216.geometry} material={materials.Wall_white} position={[0.92, 3.51, 0.58]} scale={1.89} />
      <mesh geometry={nodes.Object_254.geometry} material={materials.lENTA} position={[-0.99, 2.03, -1.89]} rotation={[-Math.PI, 0, -0.62]} scale={[-0.14, 0.08, 0.08]} />
      <mesh geometry={nodes.Object_256.geometry} material={materials.lENTA} position={[-0.99, 1.73, -1.89]} rotation={[-Math.PI, 0, -2.42]} scale={[-0.14, 0.08, 0.08]} />
      <mesh geometry={nodes.Object_258.geometry} material={materials.lENTA} position={[-0.59, 1.73, -1.88]} rotation={[-Math.PI, 0, 2.55]} scale={[-0.14, 0.08, 0.08]} />
      <mesh geometry={nodes.Object_260.geometry} material={materials.lENTA} position={[-0.59, 2.03, -1.88]} rotation={[Math.PI, 0, 0.68]} scale={[-0.14, 0.08, 0.08]} />
      <mesh geometry={nodes.Object_267.geometry} material={materials.lENTA} position={[-1.59, 2.22, -1.88]} rotation={[2.88, -0.01, 0.64]} scale={[-0.14, 0.08, 0.08]} />
      <mesh geometry={nodes.Object_269.geometry} material={materials.lENTA} position={[-1.62, 1.86, -1.88]} rotation={[-3.06, -0.26, 2.53]} scale={[-0.14, 0.08, 0.08]} />
      <mesh geometry={nodes.Object_271.geometry} material={materials.lENTA} position={[-1.16, 1.86, -1.88]} rotation={[2.93, 0.02, -2.71]} scale={[-0.14, 0.08, 0.08]} />
      <mesh geometry={nodes.Object_273.geometry} material={materials.lENTA} position={[-1.2, 2.22, -1.88]} rotation={[-3.05, -0.23, -0.52]} scale={[-0.14, 0.08, 0.08]} />
      <mesh geometry={nodes.Object_275.geometry} material={materials.lENTA} position={[-1.05, 2.84, -1.89]} rotation={[-Math.PI, 0, -0.62]} scale={[-0.18, 0.1, 0.1]} />
      <mesh geometry={nodes.Object_277.geometry} material={materials.lENTA} position={[-0.42, 2.84, -1.88]} rotation={[Math.PI, 0, 0.68]} scale={[-0.15, 0.09, 0.09]} />
      <mesh geometry={nodes.Object_279.geometry} material={materials.lENTA} position={[-1.06, 2.22, -1.89]} rotation={[-Math.PI, 0, -2.42]} scale={[-0.14, 0.08, 0.08]} />
      <mesh geometry={nodes.Object_281.geometry} material={materials.lENTA} position={[-0.42, 2.22, -1.88]} rotation={[-Math.PI, 0, 2.55]} scale={[-0.14, 0.08, 0.08]} />
      <mesh geometry={nodes.Object_283.geometry} material={materials.lENTA} position={[0.07, 1.53, -1.88]} rotation={[Math.PI, 0, 0.69]} scale={[-0.15, 0.1, 0.08]} />
      <mesh geometry={nodes.Object_285.geometry} material={materials.lENTA} position={[0.98, 1.53, -1.88]} rotation={[Math.PI, 0, 0.69]} scale={[-0.15, 0.1, 0.08]} />
      <mesh geometry={nodes.Object_287.geometry} material={materials.lENTA} position={[0.68, 2.25, -1.88]} rotation={[-Math.PI, 0, 2.55]} scale={[-0.14, 0.08, 0.08]} />
      <mesh geometry={nodes.Object_289.geometry} material={materials.lENTA} position={[-0.26, 2.25, -1.88]} rotation={[-Math.PI, 0, -2.3]} scale={[-0.14, 0.08, 0.08]} />
      <mesh geometry={nodes.Object_291.geometry} material={materials.lENTA} position={[1.02, 2.22, -1.88]} rotation={[-Math.PI, 0, -2.23]} scale={[-0.14, 0.08, 0.08]} />
      <mesh geometry={nodes.Object_300.geometry} material={materials['Keyboard_rough.001']} position={[-0.11, 0.9, -1.68]} rotation={[0, -1.27, 0]} scale={[1.31, 1.55, 1.55]} />
      <mesh geometry={nodes.Object_335.geometry} material={materials.material_0} position={[-1.09, 0.95, -0.65]} scale={[0.16, 0.03, 0.14]} />
      <mesh geometry={nodes.Object_337.geometry} material={materials.material_0} position={[-1.6, 1.41, -0.37]} />
      <mesh geometry={nodes.Object_348.geometry} material={materials['Material.008']} position={[1.15, 1.27, -1.26]} rotation={[-1.76, -0.84, -2.09]} />
    </group>
  )
}

useGLTF.preload('/Room-transformed.glb')
