/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Survilence.gltf --transform
Author: ra_fuq (https://sketchfab.com/nevidaes)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/surveillance-room-7fd56cd3917443a99966352beefd8304
Title: Surveillance room
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Survilence-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.19}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[10.91, -4.45, 11.01]}>
            <mesh geometry={nodes.Object_6.geometry} material={materials.Shading2_cables} />
            <mesh geometry={nodes.Object_7.geometry} material={materials.Shading2_cables} />
            <mesh geometry={nodes.Object_8.geometry} material={materials.Shading2_cables} />
          </group>
          <group position={[10.91, -4.45, 11.01]}>
            <mesh geometry={nodes.Object_10.geometry} material={materials.Shading1} />
            <mesh geometry={nodes.Object_11.geometry} material={materials.Shading1} />
          </group>
          <mesh geometry={nodes.Object_4.geometry} material={materials.material} position={[10.91, -4.45, 11.01]} />
          <mesh geometry={nodes.Object_13.geometry} material={materials.Lumires} position={[10.91, -4.45, 11.01]} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.Shading1} position={[10.91, -4.45, 11.01]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Survilence-transformed.glb')
